### ISSUE TITLE
Lua Error when hovering recipe links

### ISSUE THREAD

**Issue by Agramon** [Shands28/ConduitHelper#1]
I receive following lua error when hovering over recipe links, like cooking ones.

Lua error:
```
9x Usage: local result = C_Soulbinds.IsItemConduitByItemInfo(itemInfo)
[string "=[C]"]: in function `IsItemConduitByItemInfo'
[string "@ConduitHelper\Core.lua"]:31: in function <ConduitHelper\Core.lua:29>
[string "=[C]"]: ?
[string "=[C]"]: ?
```

Test ingame:
`/script DEFAULT_CHAT_FRAME:AddMessage("\124cffffd000\124Henchant:338100\124h[Cooking: Arden Apple Pie]\124h\124r");`

**Comment by Shands28** [comment]
Resolved on commit https://github.com/Shands28/ConduitHelper/commit/5567ace1d6de20bdb2ecd234735b43b6e1232c1a.

Thanks for the bug report.
